Feat/data store in askar
digicatapult/veritable-cloudagent pull request #51
Opened 2024-05-03 08:52 UTC by Ellenn-A

# Changes 
- postgres container added to stack to all `docker-compose files`
-  Askar configured for postgres backend

### Ticket: 
- https://digicatapult.atlassian.net/browse/VR-15

2024-05-03 11:28 UTC, jonmattgray commented on docker-compose.yml
>      command: --ipfs-origin http://localhost:5001 --config /config.json
missing `--postgres-host`?

2024-05-03 11:29 UTC, jonmattgray commented on samples/cliConfig.json
> +  "logLevel": 0,
logLevel change?

2024-05-03 11:30 UTC, jonmattgray commented on src/cli.ts
> +  .option(' backup-before-storage-update', {
extra space character in the option

2024-05-03 11:33 UTC, jonmattgray commented on samples/cliConfig.json
> +  "postgresHost": "alice-agent-postgres:5432",
maybe no alice specific values? cliConfig also gets used by other personas

2024-05-03 11:34 UTC, jonmattgray commented on src/utils/agent.ts
> +import { AskarModule, AskarWalletPostgresStorageConfig } from '@credo-ts/askar'
unused type to remove

2024-05-03 12:12 UTC, mattdean-digicatapult commented on samples/cliConfig.json
> +  "postgresHost": "alice-agent-postgres:5432",
to be picky this isn't a host, this is a host and a port. I'd consider splitting them into separate config items

2024-05-03 14:22 UTC, jonmattgray approved these changes

2024-05-03 14:59 UTC, jonmattgray submitted a review, later dismissed

2024-05-03 15:10 UTC, jonmattgray submitted a review, later dismissed

2024-05-07 09:47 UTC, msterle requested changes

2024-05-07 09:47 UTC, msterle commented on src/cli.ts
> +      storage: {
As @dblane-digicatapult mentioned in slack, we should probably put this behind a flag so that we can still run with the default sqlite storage.

2024-05-07 09:47 UTC, msterle commented on src/cli.ts
> +  .option('backup-before-storage-update', {
Backups will error out if we are using askar-postgres, so we should not allow this option to be true if postgres is being used

2024-05-07 16:52 UTC, msterle approved these changes
👍

2024-05-09 08:46 UTC, merged