POST /connections
digicatapult/veritable-cloudagent pull request #84
Opened 2024-05-22 09:10 UTC by jonmattgray

Move the POST `/connections` route from `nice-agent-portal` https://github.com/digicatapult/nice-agent-portal/pull/59

2024-05-22 09:21 UTC, Ellenn-A approved these changes
looks good to me

2024-05-23 10:32 UTC, msterle requested changes

2024-05-23 10:32 UTC, msterle commented on src/controllers/connections/ConnectionController.ts
> +    const connections = await connectionRepository.findByQuery(this.agent.context, {
I'd suggest we use the APIs as opposed to internals (Service, Repository, etc) as these are subject to semver, whereas internals can change at any time. I realise we use the internals elsewhere, even in this file, but in this particular case, the API exposes the functionality we need: https://github.com/openwallet-foundation/credo-ts/blob/main/packages/core/src/modules/connections/ConnectionsApi.ts#L553C16-L553C35

2024-05-23 13:03 UTC, msterle approved these changes
👍

2024-05-23 13:19 UTC, merged